import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ThemeAppProvider from './components/ThemeAppProvider';
import Header from './components/Header';
import Context from './components/Context';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'link shortening',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeAppProvider>
        <body className={`${inter.className} `}>
          <Context>
          <Header />
          <main className="container mx-auto ">{children}</main>
          </Context>
        </body>
      </ThemeAppProvider>
    </html>
  );
}
